CREATE SEQUENCE seq_roles START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_divisions START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_districts START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_upazilas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_disaster_types START WITH 1 INCREMENT BY 1;