-- ============================================================
-- DIEMS — Create Table: DISASTERS
-- Module: Disaster Database (Core Table)
-- Oracle 24.3.1
-- ============================================================

CREATE TABLE DISASTERS (
    DISASTER_ID          NUMBER PRIMARY KEY,
    DISASTER_NAME        VARCHAR2(150) NOT NULL,
    TYPE_ID              NUMBER        NOT NULL,
    SEVERITY_LEVEL_ID    NUMBER        NOT NULL,
    DISTRICT             VARCHAR2(100) NOT NULL,
    DIVISION             VARCHAR2(100),
    LATITUDE             NUMBER(10, 6),
    LONGITUDE            NUMBER(10, 6),
    START_DATE           TIMESTAMP     NOT NULL,
    END_DATE             TIMESTAMP,
    STATUS               VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    AFFECTED_POPULATION  NUMBER        DEFAULT 0,
    CASUALTIES           NUMBER        DEFAULT 0,
    INJURED              NUMBER        DEFAULT 0,
    DISPLACED            NUMBER        DEFAULT 0,
    ESTIMATED_DAMAGE     NUMBER(18, 2) DEFAULT 0,   -- in BDT (Taka)
    DESCRIPTION          CLOB,
    WEATHER_CONDITIONS   VARCHAR2(300),
    RESPONSE_TEAMS       NUMBER        DEFAULT 0,
    REPORTED_BY          NUMBER,
    CREATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP,

    CONSTRAINT FK_DISASTERS_TYPE
        FOREIGN KEY (TYPE_ID)
        REFERENCES DISASTER_TYPES(TYPE_ID),

    CONSTRAINT FK_DISASTERS_SEVERITY
        FOREIGN KEY (SEVERITY_LEVEL_ID)
        REFERENCES SEVERITY_LEVELS(LEVEL_ID),

    CONSTRAINT FK_DISASTERS_REPORTER
        FOREIGN KEY (REPORTED_BY)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_DISASTERS_STATUS
        CHECK (STATUS IN ('ACTIVE', 'MONITORING', 'CONTROLLED', 'RESOLVED')),

    CONSTRAINT CHK_DISASTERS_DATES
        CHECK (END_DATE IS NULL OR END_DATE >= START_DATE)
);

-- Indexes for performance
CREATE INDEX IDX_DISASTERS_STATUS    ON DISASTERS(STATUS);
CREATE INDEX IDX_DISASTERS_DISTRICT  ON DISASTERS(DISTRICT);
CREATE INDEX IDX_DISASTERS_TYPE      ON DISASTERS(TYPE_ID);
CREATE INDEX IDX_DISASTERS_SEVERITY  ON DISASTERS(SEVERITY_LEVEL_ID);
CREATE INDEX IDX_DISASTERS_START     ON DISASTERS(START_DATE);

COMMENT ON TABLE  DISASTERS                    IS 'Core disaster records - central table of the system';
COMMENT ON COLUMN DISASTERS.STATUS             IS 'ACTIVE=ongoing, MONITORING=watch, CONTROLLED=contained, RESOLVED=ended';
COMMENT ON COLUMN DISASTERS.ESTIMATED_DAMAGE   IS 'Estimated financial damage in Bangladesh Taka (BDT)';
COMMENT ON COLUMN DISASTERS.LATITUDE           IS 'Geographic latitude of disaster epicenter';
COMMENT ON COLUMN DISASTERS.LONGITUDE          IS 'Geographic longitude of disaster epicenter';
