-- ============================================================
-- DIEMS — Create Table: RESOURCES
-- Module: Emergency Resource Management
-- Oracle 24.3.1
-- ============================================================

CREATE TABLE RESOURCES (
    RESOURCE_ID        NUMBER PRIMARY KEY,
    CATEGORY_ID        NUMBER        NOT NULL,
    RESOURCE_NAME      VARCHAR2(150) NOT NULL,
    TOTAL_QUANTITY     NUMBER        DEFAULT 0  NOT NULL,
    AVAILABLE_QUANTITY NUMBER        DEFAULT 0  NOT NULL,
    RESERVED_QUANTITY  NUMBER        DEFAULT 0,
    UNIT_COST          NUMBER(14, 2) DEFAULT 0,   -- Cost per unit in BDT
    STORAGE_LOCATION   VARCHAR2(200),
    SUPPLIER_NAME      VARCHAR2(100),
    SUPPLIER_CONTACT   VARCHAR2(20),
    EXPIRY_DATE        DATE,
    LAST_RESTOCKED     TIMESTAMP,
    LAST_UPDATED       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_BY         NUMBER,
    NOTES              VARCHAR2(500),

    CONSTRAINT FK_RESOURCES_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES RESOURCE_CATEGORIES(CATEGORY_ID),

    CONSTRAINT FK_RESOURCES_UPDATED_BY
        FOREIGN KEY (UPDATED_BY)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_RESOURCES_QTY
        CHECK (AVAILABLE_QUANTITY >= 0 AND TOTAL_QUANTITY >= 0),

    CONSTRAINT CHK_RESOURCES_AVAILABLE
        CHECK (AVAILABLE_QUANTITY <= TOTAL_QUANTITY)
);

CREATE INDEX IDX_RESOURCES_CATEGORY  ON RESOURCES(CATEGORY_ID);
CREATE INDEX IDX_RESOURCES_NAME      ON RESOURCES(RESOURCE_NAME);

COMMENT ON TABLE  RESOURCES                    IS 'Emergency resource inventory with quantity tracking';
COMMENT ON COLUMN RESOURCES.TOTAL_QUANTITY     IS 'Total stock including reserved and available';
COMMENT ON COLUMN RESOURCES.AVAILABLE_QUANTITY IS 'Currently available for distribution';
COMMENT ON COLUMN RESOURCES.RESERVED_QUANTITY  IS 'Reserved for specific operations but not yet distributed';
