-- ============================================================
-- DIEMS — Create Table: RESOURCE_DISTRIBUTION
-- Module: Emergency Resource Management
-- Oracle 24.3.1
-- NOTE: INVENTORY_UPDATE_TRG fires AFTER INSERT on this table
-- ============================================================

CREATE TABLE RESOURCE_DISTRIBUTION (
    DIST_ID          NUMBER PRIMARY KEY,
    RESOURCE_ID      NUMBER        NOT NULL,
    QUANTITY         NUMBER        NOT NULL,
    SHELTER_ID       NUMBER,
    DISASTER_ID      NUMBER,
    PRIORITY         VARCHAR2(20)  DEFAULT 'Normal',
    DISTRIBUTED_BY   NUMBER        NOT NULL,
    DISTRIBUTED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
    STATUS           VARCHAR2(20)  DEFAULT 'Pending' NOT NULL,
    DELIVERY_DATE    TIMESTAMP,
    RECEIVED_BY      VARCHAR2(100),
    NOTES            VARCHAR2(500),

    CONSTRAINT FK_DIST_RESOURCE
        FOREIGN KEY (RESOURCE_ID)
        REFERENCES RESOURCES(RESOURCE_ID),

    CONSTRAINT FK_DIST_SHELTER
        FOREIGN KEY (SHELTER_ID)
        REFERENCES SHELTERS(SHELTER_ID),

    CONSTRAINT FK_DIST_DISASTER
        FOREIGN KEY (DISASTER_ID)
        REFERENCES DISASTERS(DISASTER_ID),

    CONSTRAINT FK_DIST_BY
        FOREIGN KEY (DISTRIBUTED_BY)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_DIST_STATUS
        CHECK (STATUS IN ('Pending', 'In Transit', 'Delivered', 'Cancelled')),

    CONSTRAINT CHK_DIST_PRIORITY
        CHECK (PRIORITY IN ('Immediate', 'High', 'Normal', 'Low')),

    CONSTRAINT CHK_DIST_QTY
        CHECK (QUANTITY > 0)
);

CREATE INDEX IDX_DIST_RESOURCE  ON RESOURCE_DISTRIBUTION(RESOURCE_ID);
CREATE INDEX IDX_DIST_SHELTER   ON RESOURCE_DISTRIBUTION(SHELTER_ID);
CREATE INDEX IDX_DIST_DISASTER  ON RESOURCE_DISTRIBUTION(DISASTER_ID);
CREATE INDEX IDX_DIST_STATUS    ON RESOURCE_DISTRIBUTION(STATUS);
CREATE INDEX IDX_DIST_DATE      ON RESOURCE_DISTRIBUTION(DISTRIBUTED_AT);

COMMENT ON TABLE  RESOURCE_DISTRIBUTION        IS 'Log of all resource distribution events - triggers INVENTORY_UPDATE_TRG';
COMMENT ON COLUMN RESOURCE_DISTRIBUTION.STATUS IS 'Pending=queued, In Transit=moving, Delivered=received, Cancelled=aborted';
