-- ============================================================
-- DIEMS — 01_create_tables.sql
-- Module: Master Schema Tables Builder
-- Oracle 11g Compatibility
-- ============================================================

PROMPT Creating ROLES table...
@@Tables/create_table_roles.sql

PROMPT Creating PERMISSIONS table...
@@Tables/create_table_permissions.sql

PROMPT Creating USERS table...
@@Tables/create_table_users.sql

PROMPT Creating USER_PERMISSIONS table...
@@Tables/create_table_user_permissions.sql

PROMPT Creating DISASTER_TYPES table...
@@Tables/create_table_disaster_types.sql

PROMPT Creating SEVERITY_LEVELS table...
@@Tables/create_table_severity_levels.sql

PROMPT Creating DISASTERS table...
@@Tables/create_table_disasters.sql

PROMPT Creating AFFECTED_AREAS table...
@@Tables/create_table_affected_areas.sql

PROMPT Creating SHELTERS table...
@@Tables/create_table_shelters.sql

PROMPT Creating SHELTER_CAPACITY table...
@@Tables/create_table_shelter_capacity.sql

PROMPT Creating VICTIMS table...
@@Tables/create_table_victims.sql

PROMPT Creating FAMILY_MEMBERS table...
@@Tables/create_table_family_members.sql

PROMPT Creating MISSING_PERSONS table...
@@Tables/create_table_missing_persons.sql

PROMPT Creating RESOURCE_CATEGORIES table...
@@Tables/create_table_resource_categories.sql

PROMPT Creating RESOURCES table...
@@Tables/create_table_resources.sql

PROMPT Creating RESOURCE_DISTRIBUTION table...
@@Tables/create_table_resource_distribution.sql

PROMPT Creating SHELTER_RESIDENTS table...
@@Tables/create_table_shelter_residents.sql

PROMPT Creating HOSPITALS table...
@@Tables/create_table_hospitals.sql

PROMPT Creating DOCTORS table...
@@Tables/create_table_doctors.sql

PROMPT Creating AMBULANCES table...
@@Tables/create_table_ambulances.sql

PROMPT Creating MEDICAL_REQUESTS table...
@@Tables/create_table_medical_requests.sql

PROMPT Creating VOLUNTEERS table...
@@Tables/create_table_volunteers.sql

PROMPT Creating SKILLS table...
@@Tables/create_table_skills.sql

PROMPT Creating VOLUNTEER_SKILLS table...
@@Tables/create_table_volunteer_skills.sql

PROMPT Creating VOLUNTEER_ASSIGNMENTS table...
@@Tables/create_table_volunteer_assignments.sql

PROMPT Creating INCIDENT_REPORTS table...
@@Tables/create_table_incident_reports.sql

PROMPT Creating REPORT_ATTACHMENTS table...
@@Tables/create_table_report_attachments.sql

PROMPT Creating AUDIT_LOG table...
@@Tables/create_table_audit_log.sql

PROMPT All tables created successfully!
