-- ============================================================
-- DIEMS — 02_create_sequences.sql
-- Module: Sequences & Auto-increment Triggers for Oracle 11g
-- Oracle 11.2.0.2.0 Compatibility
-- ============================================================

PROMPT Creating sequences...

CREATE SEQUENCE ROLES_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE PERMISSIONS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USERS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE USER_PERMISSIONS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DISASTER_TYPES_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE SEVERITY_LEVELS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE DISASTERS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE AFFECTED_AREAS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE SHELTERS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE SHELTER_CAPACITY_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE VICTIMS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE FAMILY_MEMBERS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE MISSING_PERSONS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE RESOURCE_CATEGORIES_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE RESOURCES_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE RESOURCE_DISTRIBUTION_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE SHELTER_RESIDENTS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE HOSPITALS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE DOCTORS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE AMBULANCES_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE MEDICAL_REQUESTS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE VOLUNTEERS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE SKILLS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE VOLUNTEER_SKILLS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE VOLUNTEER_ASSIGNMENTS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE INCIDENT_REPORTS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE REPORT_ATTACHMENTS_SEQ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 10 INCREMENT BY 1;

PROMPT Creating auto-increment triggers...

-- 1. ROLES
CREATE OR REPLACE TRIGGER T_ROLES_BI
BEFORE INSERT ON ROLES
FOR EACH ROW
BEGIN
  IF :new.ROLE_ID IS NULL THEN
    SELECT ROLES_SEQ.NEXTVAL INTO :new.ROLE_ID FROM dual;
  END IF;
END;
/

-- 2. PERMISSIONS
CREATE OR REPLACE TRIGGER T_PERMISSIONS_BI
BEFORE INSERT ON PERMISSIONS
FOR EACH ROW
BEGIN
  IF :new.PERMISSION_ID IS NULL THEN
    SELECT PERMISSIONS_SEQ.NEXTVAL INTO :new.PERMISSION_ID FROM dual;
  END IF;
END;
/

-- 3. USERS
CREATE OR REPLACE TRIGGER T_USERS_BI
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :new.USER_ID IS NULL THEN
    SELECT USERS_SEQ.NEXTVAL INTO :new.USER_ID FROM dual;
  END IF;
END;
/

-- 4. USER_PERMISSIONS
CREATE OR REPLACE TRIGGER T_USER_PERMISSIONS_BI
BEFORE INSERT ON USER_PERMISSIONS
FOR EACH ROW
BEGIN
  IF :new.UP_ID IS NULL THEN
    SELECT USER_PERMISSIONS_SEQ.NEXTVAL INTO :new.UP_ID FROM dual;
  END IF;
END;
/

-- 5. DISASTER_TYPES
CREATE OR REPLACE TRIGGER T_DISASTER_TYPES_BI
BEFORE INSERT ON DISASTER_TYPES
FOR EACH ROW
BEGIN
  IF :new.TYPE_ID IS NULL THEN
    SELECT DISASTER_TYPES_SEQ.NEXTVAL INTO :new.TYPE_ID FROM dual;
  END IF;
END;
/

-- 6. SEVERITY_LEVELS
CREATE OR REPLACE TRIGGER T_SEVERITY_LEVELS_BI
BEFORE INSERT ON SEVERITY_LEVELS
FOR EACH ROW
BEGIN
  IF :new.LEVEL_ID IS NULL THEN
    SELECT SEVERITY_LEVELS_SEQ.NEXTVAL INTO :new.LEVEL_ID FROM dual;
  END IF;
END;
/

-- 7. DISASTERS
CREATE OR REPLACE TRIGGER T_DISASTERS_BI
BEFORE INSERT ON DISASTERS
FOR EACH ROW
BEGIN
  IF :new.DISASTER_ID IS NULL THEN
    SELECT DISASTERS_SEQ.NEXTVAL INTO :new.DISASTER_ID FROM dual;
  END IF;
END;
/

-- 8. AFFECTED_AREAS
CREATE OR REPLACE TRIGGER T_AFFECTED_AREAS_BI
BEFORE INSERT ON AFFECTED_AREAS
FOR EACH ROW
BEGIN
  IF :new.AREA_ID IS NULL THEN
    SELECT AFFECTED_AREAS_SEQ.NEXTVAL INTO :new.AREA_ID FROM dual;
  END IF;
END;
/

-- 9. SHELTERS
CREATE OR REPLACE TRIGGER T_SHELTERS_BI
BEFORE INSERT ON SHELTERS
FOR EACH ROW
BEGIN
  IF :new.SHELTER_ID IS NULL THEN
    SELECT SHELTERS_SEQ.NEXTVAL INTO :new.SHELTER_ID FROM dual;
  END IF;
END;
/

-- 10. SHELTER_CAPACITY
CREATE OR REPLACE TRIGGER T_SHELTER_CAPACITY_BI
BEFORE INSERT ON SHELTER_CAPACITY
FOR EACH ROW
BEGIN
  IF :new.SC_ID IS NULL THEN
    SELECT SHELTER_CAPACITY_SEQ.NEXTVAL INTO :new.SC_ID FROM dual;
  END IF;
END;
/

-- 11. VICTIMS
CREATE OR REPLACE TRIGGER T_VICTIMS_BI
BEFORE INSERT ON VICTIMS
FOR EACH ROW
BEGIN
  IF :new.VICTIM_ID IS NULL THEN
    SELECT VICTIMS_SEQ.NEXTVAL INTO :new.VICTIM_ID FROM dual;
  END IF;
END;
/

-- 12. FAMILY_MEMBERS
CREATE OR REPLACE TRIGGER T_FAMILY_MEMBERS_BI
BEFORE INSERT ON FAMILY_MEMBERS
FOR EACH ROW
BEGIN
  IF :new.FM_ID IS NULL THEN
    SELECT FAMILY_MEMBERS_SEQ.NEXTVAL INTO :new.FM_ID FROM dual;
  END IF;
END;
/

-- 13. MISSING_PERSONS
CREATE OR REPLACE TRIGGER T_MISSING_PERSONS_BI
BEFORE INSERT ON MISSING_PERSONS
FOR EACH ROW
BEGIN
  IF :new.MP_ID IS NULL THEN
    SELECT MISSING_PERSONS_SEQ.NEXTVAL INTO :new.MP_ID FROM dual;
  END IF;
END;
/

-- 14. RESOURCE_CATEGORIES
CREATE OR REPLACE TRIGGER T_RESOURCE_CATEGORIES_BI
BEFORE INSERT ON RESOURCE_CATEGORIES
FOR EACH ROW
BEGIN
  IF :new.CATEGORY_ID IS NULL THEN
    SELECT RESOURCE_CATEGORIES_SEQ.NEXTVAL INTO :new.CATEGORY_ID FROM dual;
  END IF;
END;
/

-- 15. RESOURCES
CREATE OR REPLACE TRIGGER T_RESOURCES_BI
BEFORE INSERT ON RESOURCES
FOR EACH ROW
BEGIN
  IF :new.RESOURCE_ID IS NULL THEN
    SELECT RESOURCES_SEQ.NEXTVAL INTO :new.RESOURCE_ID FROM dual;
  END IF;
END;
/

-- 16. RESOURCE_DISTRIBUTION
CREATE OR REPLACE TRIGGER T_RESOURCE_DIST_BI
BEFORE INSERT ON RESOURCE_DISTRIBUTION
FOR EACH ROW
BEGIN
  IF :new.DIST_ID IS NULL THEN
    SELECT RESOURCE_DISTRIBUTION_SEQ.NEXTVAL INTO :new.DIST_ID FROM dual;
  END IF;
END;
/

-- 17. SHELTER_RESIDENTS
CREATE OR REPLACE TRIGGER T_SHELTER_RESIDENTS_BI
BEFORE INSERT ON SHELTER_RESIDENTS
FOR EACH ROW
BEGIN
  IF :new.SR_ID IS NULL THEN
    SELECT SHELTER_RESIDENTS_SEQ.NEXTVAL INTO :new.SR_ID FROM dual;
  END IF;
END;
/

-- 18. HOSPITALS
CREATE OR REPLACE TRIGGER T_HOSPITALS_BI
BEFORE INSERT ON HOSPITALS
FOR EACH ROW
BEGIN
  IF :new.HOSPITAL_ID IS NULL THEN
    SELECT HOSPITALS_SEQ.NEXTVAL INTO :new.HOSPITAL_ID FROM dual;
  END IF;
END;
/

-- 19. DOCTORS
CREATE OR REPLACE TRIGGER T_DOCTORS_BI
BEFORE INSERT ON DOCTORS
FOR EACH ROW
BEGIN
  IF :new.DOCTOR_ID IS NULL THEN
    SELECT DOCTORS_SEQ.NEXTVAL INTO :new.DOCTOR_ID FROM dual;
  END IF;
END;
/

-- 20. AMBULANCES
CREATE OR REPLACE TRIGGER T_AMBULANCES_BI
BEFORE INSERT ON AMBULANCES
FOR EACH ROW
BEGIN
  IF :new.AMBULANCE_ID IS NULL THEN
    SELECT AMBULANCES_SEQ.NEXTVAL INTO :new.AMBULANCE_ID FROM dual;
  END IF;
END;
/

-- 21. MEDICAL_REQUESTS
CREATE OR REPLACE TRIGGER T_MEDICAL_REQUESTS_BI
BEFORE INSERT ON MEDICAL_REQUESTS
FOR EACH ROW
BEGIN
  IF :new.REQUEST_ID IS NULL THEN
    SELECT MEDICAL_REQUESTS_SEQ.NEXTVAL INTO :new.REQUEST_ID FROM dual;
  END IF;
END;
/

-- 22. VOLUNTEERS
CREATE OR REPLACE TRIGGER T_VOLUNTEERS_BI
BEFORE INSERT ON VOLUNTEERS
FOR EACH ROW
BEGIN
  IF :new.VOLUNTEER_ID IS NULL THEN
    SELECT VOLUNTEERS_SEQ.NEXTVAL INTO :new.VOLUNTEER_ID FROM dual;
  END IF;
END;
/

-- 23. SKILLS
CREATE OR REPLACE TRIGGER T_SKILLS_BI
BEFORE INSERT ON SKILLS
FOR EACH ROW
BEGIN
  IF :new.SKILL_ID IS NULL THEN
    SELECT SKILLS_SEQ.NEXTVAL INTO :new.SKILL_ID FROM dual;
  END IF;
END;
/

-- 24. VOLUNTEER_SKILLS
CREATE OR REPLACE TRIGGER T_VOLUNTEER_SKILLS_BI
BEFORE INSERT ON VOLUNTEER_SKILLS
FOR EACH ROW
BEGIN
  IF :new.VS_ID IS NULL THEN
    SELECT VOLUNTEER_SKILLS_SEQ.NEXTVAL INTO :new.VS_ID FROM dual;
  END IF;
END;
/

-- 25. VOLUNTEER_ASSIGNMENTS
CREATE OR REPLACE TRIGGER T_VOLUNTEER_ASSIGN_BI
BEFORE INSERT ON VOLUNTEER_ASSIGNMENTS
FOR EACH ROW
BEGIN
  IF :new.ASSIGNMENT_ID IS NULL THEN
    SELECT VOLUNTEER_ASSIGNMENTS_SEQ.NEXTVAL INTO :new.ASSIGNMENT_ID FROM dual;
  END IF;
END;
/

-- 26. INCIDENT_REPORTS
CREATE OR REPLACE TRIGGER T_INCIDENT_REPORTS_BI
BEFORE INSERT ON INCIDENT_REPORTS
FOR EACH ROW
BEGIN
  IF :new.REPORT_ID IS NULL THEN
    SELECT INCIDENT_REPORTS_SEQ.NEXTVAL INTO :new.REPORT_ID FROM dual;
  END IF;
END;
/

-- 27. REPORT_ATTACHMENTS
CREATE OR REPLACE TRIGGER T_REPORT_ATTACHMENTS_BI
BEFORE INSERT ON REPORT_ATTACHMENTS
FOR EACH ROW
BEGIN
  IF :new.ATTACHMENT_ID IS NULL THEN
    SELECT REPORT_ATTACHMENTS_SEQ.NEXTVAL INTO :new.ATTACHMENT_ID FROM dual;
  END IF;
END;
/

-- 28. AUDIT_LOG
CREATE OR REPLACE TRIGGER T_AUDIT_LOG_BI
BEFORE INSERT ON AUDIT_LOG
FOR EACH ROW
BEGIN
  IF :new.LOG_ID IS NULL THEN
    SELECT AUDIT_LOG_SEQ.NEXTVAL INTO :new.LOG_ID FROM dual;
  END IF;
END;
/
