-- ============================================================
-- DIEMS — 07_sample_data.sql
-- Oracle 24.3.1
--
-- PURPOSE:
--   Seeds realistic, rich test data for the Disaster Intelligence
--   and Emergency Management System (DIEMS).
--   Includes users, disasters, shelters, victims, resources,
--   hospitals, volunteers, and incident reports in Bangladesh context.
-- ============================================================

SET DEFINE OFF;

-- 1. Seed Roles
INSERT INTO ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, IS_ACTIVE)
VALUES (1, 'Admin', 'System administrator with full system permissions', 1);

INSERT INTO ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, IS_ACTIVE)
VALUES (2, 'Official', 'Government and disaster management authority official', 1);

INSERT INTO ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, IS_ACTIVE)
VALUES (3, 'Responder', 'Emergency responder, medical personnel, or shelter manager', 1);

INSERT INTO ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, IS_ACTIVE)
VALUES (4, 'Volunteer', 'Registered volunteer assisting in relief operations', 1);

INSERT INTO ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, IS_ACTIVE)
VALUES (5, 'Citizen', 'General public user who can report incidents and request help', 1);

COMMIT;

-- 2. Seed Users
-- Passwords are dummy SHA256 hashes of the username (e.g. SHA256 of 'admin' is '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918')
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, EMAIL, FULL_NAME, PHONE, NID, ROLE_ID, DISTRICT, ADDRESS, IS_ACTIVE)
VALUES (1, 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'admin@diems.gov.bd', 'Dr. Majharul Shajid', '+8801711111111', '19902692512345678', 1, 'Dhaka', 'Secretariat, Dhaka', 1);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, EMAIL, FULL_NAME, PHONE, NID, ROLE_ID, DISTRICT, ADDRESS, IS_ACTIVE)
VALUES (2, 'official', '8e434f8a379435b6df888062ec7e58a74bdf7f4ff3b20755f1146316cc8c02c0', 'official.sylhet@diems.gov.bd', 'Abu Taher (DD, DDMA)', '+8801822222222', '19852692587654321', 2, 'Sylhet', 'District Administration Office, Sylhet', 1);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, EMAIL, FULL_NAME, PHONE, NID, ROLE_ID, DISTRICT, ADDRESS, IS_ACTIVE)
VALUES (3, 'responder', '4cb87948a73505c1d683a48e71fc997c4e5cf92b8d0b271a2d591873e343714b', 'fire.sylhet@diems.gov.bd', 'Kabir Hossain (Station Officer)', '+8801933333333', '19882692544455566', 3, 'Sylhet', 'Fire Service Station, Sylhet Sadar', 1);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, EMAIL, FULL_NAME, PHONE, NID, ROLE_ID, DISTRICT, ADDRESS, IS_ACTIVE)
VALUES (4, 'volunteer', '0f3e2e8df31bfab008405e3f169f464d7df643cf6289eb6e21eb23c8e4eb78b0', 'rahim.vol@diems.org', 'Abdur Rahim', '+8801544444444', '20012692599988877', 4, 'Sylhet', 'Gowainghat, Sylhet', 1);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, EMAIL, FULL_NAME, PHONE, NID, ROLE_ID, DISTRICT, ADDRESS, IS_ACTIVE)
VALUES (5, 'citizen', 'a19b882312b2e88a38b556f8f7478051783cf53f191b7d5ec92f3af58e0a3597', 'karim.citizen@gmail.com', 'Abdul Karim', '+8801655555555', '19952692511122233', 5, 'Sylhet', 'Kanaighat, Sylhet', 1);

COMMIT;

-- 3. Seed Disasters
INSERT INTO DISASTERS (DISASTER_ID, DISASTER_NAME, TYPE_ID, SEVERITY_LEVEL_ID, DISTRICT, DIVISION, LATITUDE, LONGITUDE, START_DATE, END_DATE, STATUS, AFFECTED_POPULATION, CASUALTIES, INJURED, DISPLACED, ESTIMATED_DAMAGE, DESCRIPTION, WEATHER_CONDITIONS, RESPONSE_TEAMS, REPORTED_BY)
VALUES (1, 'Sylhet Flash Floods 2026', 2, 1, 'Sylhet', 'Sylhet', 24.8949, 91.8687, TO_TIMESTAMP('2026-06-15 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'ACTIVE', 250000, 12, 45, 15000, 50000000.00, 'Heavy monsoon rains combined with upstream mountain runoff have flooded 70% of Sylhet city and surrounding upazilas.', 'Continuous torrential rain, wind speed 20 km/h', 14, 2);

INSERT INTO DISASTERS (DISASTER_ID, DISASTER_NAME, TYPE_ID, SEVERITY_LEVEL_ID, DISTRICT, DIVISION, LATITUDE, LONGITUDE, START_DATE, END_DATE, STATUS, AFFECTED_POPULATION, CASUALTIES, INJURED, DISPLACED, ESTIMATED_DAMAGE, DESCRIPTION, WEATHER_CONDITIONS, RESPONSE_TEAMS, REPORTED_BY)
VALUES (2, 'Cyclone Remal', 1, 2, 'Cox''s Bazar', 'Chattogram', 21.4395, 92.0077, TO_TIMESTAMP('2026-05-24 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-27 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'RESOLVED', 800000, 16, 120, 150000, 350000000.00, 'Severe cyclonic storm Remal made landfall near Mongla and Cox''s Bazar causing storm surges and wind damage.', 'High winds 110 km/h, heavy tidal surge', 45, 1);

INSERT INTO DISASTERS (DISASTER_ID, DISASTER_NAME, TYPE_ID, SEVERITY_LEVEL_ID, DISTRICT, DIVISION, LATITUDE, LONGITUDE, START_DATE, END_DATE, STATUS, AFFECTED_POPULATION, CASUALTIES, INJURED, DISPLACED, ESTIMATED_DAMAGE, DESCRIPTION, WEATHER_CONDITIONS, RESPONSE_TEAMS, REPORTED_BY)
VALUES (3, 'Dhaka Earthquake Watch', 3, 3, 'Dhaka', 'Dhaka', 23.8103, 90.4125, TO_TIMESTAMP('2026-06-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'MONITORING', 0, 0, 0, 0, 0.00, 'Minor tremors felt near Dhaka fault line. Continuous structural safety audits ongoing.', 'Clear skies, normal temperatures', 4, 1);

COMMIT;

-- 4. Seed Affected Areas
INSERT INTO AFFECTED_AREAS (AREA_ID, DISASTER_ID, UNION_NAME, DISTRICT, UPAZILA, AREA_KM2, POPULATION_AT_RISK, IS_EVACUATED, NOTES)
VALUES (1, 1, 'Gowainghat Sadar', 'Sylhet', 'Gowainghat', 8.5, 45000, 0, 'All main roads submerged under 4 feet water. Local bridge collapsed.');

INSERT INTO AFFECTED_AREAS (AREA_ID, DISASTER_ID, UNION_NAME, DISTRICT, UPAZILA, AREA_KM2, POPULATION_AT_RISK, IS_EVACUATED, NOTES)
VALUES (2, 1, 'Kanaighat Bazar', 'Sylhet', 'Kanaighat', 7.2, 38000, 0, 'Electricity grid offline. Water treatment plant contaminated.');

INSERT INTO AFFECTED_AREAS (AREA_ID, DISASTER_ID, UNION_NAME, DISTRICT, UPAZILA, AREA_KM2, POPULATION_AT_RISK, IS_EVACUATED, NOTES)
VALUES (3, 1, 'Sylhet Sadar Ward 10', 'Sylhet', 'Sylhet Sadar', 6.0, 60000, 0, 'Waterlogged streets. Ground floors of residential buildings flooded.');

COMMIT;

-- 5. Seed Shelters
INSERT INTO SHELTERS (SHELTER_ID, SHELTER_NAME, SHELTER_TYPE, LOCATION, DISTRICT, UPAZILA, LATITUDE, LONGITUDE, CONTACT_PERSON, CONTACT_PHONE, FACILITIES, HAS_MEDICAL, HAS_GENERATOR, HAS_WIFI, IS_ACTIVE, CREATED_BY)
VALUES (1, 'Sylhet Government College Shelter', 'General', 'College Road, Tamabil Highway, Sylhet', 'Sylhet', 'Sylhet Sadar', 24.9080, 91.8900, 'Prof. Aminul Islam', '+8801755555555', 'Food,Water,Medical,Toilets,Generator', 1, 1, 0, 1, 1);

INSERT INTO SHELTERS (SHELTER_ID, SHELTER_NAME, SHELTER_TYPE, LOCATION, DISTRICT, UPAZILA, LATITUDE, LONGITUDE, CONTACT_PERSON, CONTACT_PHONE, FACILITIES, HAS_MEDICAL, HAS_GENERATOR, HAS_WIFI, IS_ACTIVE, CREATED_BY)
VALUES (2, 'Gowainghat Primary School Shelter', 'Mixed', 'Gowainghat Bazar, Sylhet', 'Sylhet', 'Gowainghat', 25.1834, 91.9774, 'Md. Shahjahan', '+8801866666666', 'Food,Water,Toilets', 0, 0, 0, 1, 1);

COMMIT;

-- 6. Seed Shelter Capacity
INSERT INTO SHELTER_CAPACITY (SC_ID, SHELTER_ID, MAX_CAPACITY, CURRENT_OCCUPIED, AVAILABLE_BEDS, RESERVED_SPOTS, HAS_OVERFLOW)
VALUES (1, 1, 500, 0, 500, 20, 0);

INSERT INTO SHELTER_CAPACITY (SC_ID, SHELTER_ID, MAX_CAPACITY, CURRENT_OCCUPIED, AVAILABLE_BEDS, RESERVED_SPOTS, HAS_OVERFLOW)
VALUES (2, 2, 200, 0, 200, 10, 0);

COMMIT;

-- 7. Seed Victims
INSERT INTO VICTIMS (VICTIM_ID, NID, FULL_NAME, AGE, DATE_OF_BIRTH, GENDER, PHONE, EMERGENCY_CONTACT, ADDRESS, DISTRICT, DISASTER_ID, SHELTER_ID, MEDICAL_CONDITION, BLOOD_GROUP, STATUS, REGISTERED_BY)
VALUES (1, '5555566666777', 'Kalam Mia', 45, TO_DATE('1981-03-12', 'YYYY-MM-DD'), 'M', '+8801777777777', '+8801788888888', 'Village: Salutikar, Gowainghat', 'Sylhet', 1, NULL, 'Stable', 'O+', 'Displaced', 2);

INSERT INTO VICTIMS (VICTIM_ID, NID, FULL_NAME, AGE, DATE_OF_BIRTH, GENDER, PHONE, EMERGENCY_CONTACT, ADDRESS, DISTRICT, DISASTER_ID, SHELTER_ID, MEDICAL_CONDITION, BLOOD_GROUP, STATUS, REGISTERED_BY)
VALUES (2, '8888899999000', 'Sufia Begum', 38, TO_DATE('1988-08-25', 'YYYY-MM-DD'), 'F', '+8801888888888', '+8801777777777', 'Village: Salutikar, Gowainghat', 'Sylhet', 1, NULL, 'Stable', 'A+', 'Displaced', 2);

INSERT INTO VICTIMS (VICTIM_ID, NID, FULL_NAME, AGE, DATE_OF_BIRTH, GENDER, PHONE, EMERGENCY_CONTACT, ADDRESS, DISTRICT, DISASTER_ID, SHELTER_ID, MEDICAL_CONDITION, BLOOD_GROUP, STATUS, REGISTERED_BY)
VALUES (3, NULL, 'Tariqul Islam', 12, TO_DATE('2014-05-10', 'YYYY-MM-DD'), 'M', NULL, '+8801999999999', 'Village: Gowainghat Sadar', 'Sylhet', 1, NULL, 'Minor', 'B+', 'Displaced', 3);

INSERT INTO VICTIMS (VICTIM_ID, NID, FULL_NAME, AGE, DATE_OF_BIRTH, GENDER, PHONE, EMERGENCY_CONTACT, ADDRESS, DISTRICT, DISASTER_ID, SHELTER_ID, MEDICAL_CONDITION, BLOOD_GROUP, STATUS, REGISTERED_BY)
VALUES (4, '2222233333444', 'Rahima Khatun', 60, TO_DATE('1966-02-15', 'YYYY-MM-DD'), 'F', '+8801999999999', '+8801711223344', 'Village: Kanaighat', 'Sylhet', 1, NULL, 'Critical', 'AB-', 'Displaced', 3);

COMMIT;

-- 8. Seed Family Members
INSERT INTO FAMILY_MEMBERS (FM_ID, VICTIM_ID, FULL_NAME, RELATION, AGE, GENDER, IS_SEPARATED, STATUS, NOTES)
VALUES (1, 1, 'Sufia Begum', 'Spouse', 38, 'F', 0, 'Safe', 'Accompanying spouse Kalam Mia');

INSERT INTO FAMILY_MEMBERS (FM_ID, VICTIM_ID, FULL_NAME, RELATION, AGE, GENDER, IS_SEPARATED, STATUS, NOTES)
VALUES (2, 1, 'Rony Mia', 'Son', 8, 'M', 0, 'Safe', 'Accompanying son Kalam Mia');

COMMIT;

-- 9. Seed Resources
INSERT INTO RESOURCES (RESOURCE_ID, CATEGORY_ID, RESOURCE_NAME, TOTAL_QUANTITY, AVAILABLE_QUANTITY, RESERVED_QUANTITY, UNIT_COST, STORAGE_LOCATION, SUPPLIER_NAME, SUPPLIER_CONTACT, EXPIRY_DATE, LAST_RESTOCKED, UPDATED_BY)
VALUES (1, 1, 'Emergency Rice & Lentils Packet (2kg)', 5000, 5000, 200, 180.00, 'Sylhet District Warehouse', 'PRAN Foods Ltd.', '+8801711000000', TO_DATE('2026-12-31', 'YYYY-MM-DD'), SYSTIMESTAMP, 1);

INSERT INTO RESOURCES (RESOURCE_ID, CATEGORY_ID, RESOURCE_NAME, TOTAL_QUANTITY, AVAILABLE_QUANTITY, RESERVED_QUANTITY, UNIT_COST, STORAGE_LOCATION, SUPPLIER_NAME, SUPPLIER_CONTACT, EXPIRY_DATE, LAST_RESTOCKED, UPDATED_BY)
VALUES (2, 2, 'Mineral Water 5L Bottle', 10000, 10000, 500, 80.00, 'Sylhet District Warehouse', 'Fresh Water Ltd.', '+8801811000000', TO_DATE('2027-06-30', 'YYYY-MM-DD'), SYSTIMESTAMP, 1);

INSERT INTO RESOURCES (RESOURCE_ID, CATEGORY_ID, RESOURCE_NAME, TOTAL_QUANTITY, AVAILABLE_QUANTITY, RESERVED_QUANTITY, UNIT_COST, STORAGE_LOCATION, SUPPLIER_NAME, SUPPLIER_CONTACT, EXPIRY_DATE, LAST_RESTOCKED, UPDATED_BY)
VALUES (3, 3, 'Basic Medical Support Kit', 1000, 1000, 50, 450.00, 'Sylhet Civil Surgeon Office', 'Beximco Pharma', '+8801911000000', TO_DATE('2028-03-31', 'YYYY-MM-DD'), SYSTIMESTAMP, 1);

INSERT INTO RESOURCES (RESOURCE_ID, CATEGORY_ID, RESOURCE_NAME, TOTAL_QUANTITY, AVAILABLE_QUANTITY, RESERVED_QUANTITY, UNIT_COST, STORAGE_LOCATION, SUPPLIER_NAME, SUPPLIER_CONTACT, EXPIRY_DATE, LAST_RESTOCKED, UPDATED_BY)
VALUES (4, 5, 'Speed Boat 40HP Inflatable', 10, 10, 0, 350000.00, 'Sylhet Fire Service Station', 'Yamaha Marine BD', '+8801511000000', NULL, SYSTIMESTAMP, 1);

INSERT INTO RESOURCES (RESOURCE_ID, CATEGORY_ID, RESOURCE_NAME, TOTAL_QUANTITY, AVAILABLE_QUANTITY, RESERVED_QUANTITY, UNIT_COST, STORAGE_LOCATION, SUPPLIER_NAME, SUPPLIER_CONTACT, EXPIRY_DATE, LAST_RESTOCKED, UPDATED_BY)
VALUES (5, 6, 'Family Relief Tent (12x10ft)', 300, 300, 20, 12000.00, 'Sylhet District Warehouse', 'Sena Kalyan Sangstha', '+8801611000000', NULL, SYSTIMESTAMP, 1);

COMMIT;

-- 10. Seed Hospitals
INSERT INTO HOSPITALS (HOSPITAL_ID, HOSPITAL_NAME, TOTAL_BEDS, AVAILABLE_BEDS, ICU_BEDS, ICU_AVAILABLE, HAS_EMERGENCY, CONTACT_NUMBER, EMAIL, ADDRESS, DISTRICT, LATITUDE, LONGITUDE, BLOOD_O_POS, BLOOD_O_NEG, BLOOD_A_POS, IS_ACTIVE)
VALUES (1, 'Sylhet MAG Osmani Medical College Hospital', 1000, 120, 50, 4, 1, '+8801711223344', 'somch@diems.gov.bd', 'Medical College Road, Sylhet', 'Sylhet', 24.8997, 91.8519, 50, 10, 40, 1);

INSERT INTO HOSPITALS (HOSPITAL_ID, HOSPITAL_NAME, TOTAL_BEDS, AVAILABLE_BEDS, ICU_BEDS, ICU_AVAILABLE, HAS_EMERGENCY, CONTACT_NUMBER, EMAIL, ADDRESS, DISTRICT, LATITUDE, LONGITUDE, BLOOD_O_POS, BLOOD_O_NEG, BLOOD_A_POS, IS_ACTIVE)
VALUES (2, 'Mount Adora Hospital, Sylhet', 300, 65, 12, 2, 1, '+8801822334455', 'mountadora@gmail.com', 'Nayasarak, Sylhet', 'Sylhet', 24.9015, 91.8780, 20, 4, 15, 1);

COMMIT;

-- 11. Seed Doctors
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, SPECIALIZATION, PHONE, EMAIL, HOSPITAL_ID, AVAILABILITY_STATUS, IS_AVAILABLE, DEPLOYMENT_LOCATION, ASSIGNED_DISASTER_ID)
VALUES (1, 'Dr. Tanvir Rahman', 'Orthopedics', '+8801733445566', 'tanvir@somch.gov.bd', 1, 'On Duty', 1, 'Hospital Emergency Ward', 1);

INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, SPECIALIZATION, PHONE, EMAIL, HOSPITAL_ID, AVAILABILITY_STATUS, IS_AVAILABLE, DEPLOYMENT_LOCATION, ASSIGNED_DISASTER_ID)
VALUES (2, 'Dr. Sadia Islam', 'General Surgery', '+8801844556677', 'sadia.surg@gmail.com', 2, 'Available', 0, 'Mount Adora Main', NULL);

COMMIT;

-- 12. Seed Ambulances
INSERT INTO AMBULANCES (AMBULANCE_ID, VEHICLE_NO, DRIVER_NAME, DRIVER_PHONE, HOSPITAL_ID, LATITUDE, LONGITUDE, STATUS, CURRENT_LOCATION, LAST_UPDATED)
VALUES (1, 'Sylhet-Metro-Chha-11-2233', 'Mofiz Uddin', '+8801955667788', 1, 24.8997, 91.8519, 'Available', 'SOMCH Gate 2', SYSTIMESTAMP);

INSERT INTO AMBULANCES (AMBULANCE_ID, VEHICLE_NO, DRIVER_NAME, DRIVER_PHONE, HOSPITAL_ID, LATITUDE, LONGITUDE, STATUS, CURRENT_LOCATION, LAST_UPDATED)
VALUES (2, 'Sylhet-Metro-Chha-11-4455', 'Babul Mia', '+8801566778899', 2, 24.9015, 91.8780, 'Deployed', 'Gowainghat Relief Camp', SYSTIMESTAMP);

COMMIT;

-- 13. Seed Volunteers
INSERT INTO VOLUNTEERS (VOLUNTEER_ID, USER_ID, FULL_NAME, PHONE, AVAILABILITY, DISTRICT, TOTAL_MISSIONS, EMERGENCY_CONTACT)
VALUES (1, 4, 'Abdur Rahim', '+8801544444444', 'Available', 'Sylhet', 48, '+8801799887766');

COMMIT;

-- 14. Seed Volunteer Assignments
INSERT INTO VOLUNTEER_ASSIGNMENTS (ASSIGNMENT_ID, VOLUNTEER_ID, DISASTER_ID, TASK_TITLE, TASK_DESCRIPTION, START_DATE, STATUS, ASSIGNED_BY)
VALUES (1, 1, 1, 'Water Bottle Distribution', 'Distribute clean drinking water to stranded residents in Gowainghat Sadar.', TIMESTAMP '2026-06-16 09:00:00', 'Active', 2);

COMMIT;

-- 15. Seed Incident Reports
INSERT INTO INCIDENT_REPORTS (REPORT_ID, TITLE, DISASTER_ID, REPORTER_NAME, REPORTER_PHONE, INCIDENT_TYPE, DESCRIPTION, LOCATION, DISTRICT, LATITUDE, LONGITUDE, SEVERITY, STATUS, CREATED_AT, ASSIGNED_TO, RESOLUTION_NOTES)
VALUES (1, 'Road Blockage in Tamabil', 1, 'Abdul Karim', '+8801655555555', 'Infrastructure', 'Tamabil highway at Salutikar is blocked by a massive uprooted tree and 3 feet flood water. Trucks are stranded.', 'Salutikar Tamabil Road', 'Sylhet', 24.9922, 91.8790, 'High', 'Assigned', TIMESTAMP '2026-06-25 15:30:00', 3, NULL);

INSERT INTO INCIDENT_REPORTS (REPORT_ID, TITLE, DISASTER_ID, REPORTER_NAME, REPORTER_PHONE, INCIDENT_TYPE, DESCRIPTION, LOCATION, DISTRICT, LATITUDE, LONGITUDE, SEVERITY, STATUS, CREATED_AT, ASSIGNED_TO, RESOLUTION_NOTES)
VALUES (2, 'Medical Emergency at Shelter', 1, 'Citizen Report', '+8801755112233', 'Medical', 'Elderly diabetic patient in Gowainghat college shelter requires immediate insulin and medical checkup.', 'Sylhet Govt College Shelter', 'Sylhet', 24.9080, 91.8900, 'Critical', 'Resolved', TIMESTAMP '2026-06-24 10:15:00', 3, 'Patient transferred to SOMCH via Ambulance vehicle 11-4455.');

COMMIT;
